services:
  - type: web
    name: quiz-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: .
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false


  