import { Question } from '../types';

// Questions par thème avec 3 niveaux de difficulté (15 faciles, 15 moyennes, 15 difficiles)

export const questionsSimples: Record<string, Question[]> = {
  'Mathématiques': [
    // Faciles (15)
    { id: 1, question: "Combien vaut 2 + 2 ?", reponses: ["4", "3", "5", "6"], bonneReponse: 0, theme: "Mathématiques", difficulte: "facile", points: 1 },
    { id: 2, question: "Combien vaut 5 × 3 ?", reponses: ["15", "12", "18", "20"], bonneReponse: 0, theme: "Mathématiques", difficulte: "facile" },
    { id: 3, question: "Combien vaut 10 - 4 ?", reponses: ["6", "5", "7", "8"], bonneReponse: 0, theme: "Mathématiques", difficulte: "facile" },
    { id: 4, question: "Quel est le résultat de 8 ÷ 2 ?", reponses: ["4", "3", "5", "6"], bonneReponse: 0, theme: "Mathématiques", difficulte: "facile" },
    { id: 5, question: "Combien de côtés a un carré ?", reponses: ["4", "3", "5", "6"], bonneReponse: 0, theme: "Mathématiques", difficulte: "facile" },
    { id: 6, question: "Combien de côtés a un triangle ?", reponses: ["3", "4", "5", "2"], bonneReponse: 0, theme: "Mathématiques", difficulte: "facile" },
    { id: 7, question: "Combien de degrés dans un angle droit ?", reponses: ["90°", "45°", "180°", "360°"], bonneReponse: 0, theme: "Mathématiques", difficulte: "facile" },
    { id: 8, question: "Combien vaut 2³ ?", reponses: ["8", "6", "9", "4"], bonneReponse: 0, theme: "Mathématiques", difficulte: "facile" },
    { id: 9, question: "Quel est la racine carrée de 16 ?", reponses: ["4", "3", "5", "6"], bonneReponse: 0, theme: "Mathématiques", difficulte: "facile" },
    { id: 10, question: "Combien vaut 50% de 100 ?", reponses: ["50", "25", "75", "100"], bonneReponse: 0, theme: "Mathématiques", difficulte: "facile" },
    { id: 11, question: "Quel est le double de 7 ?", reponses: ["14", "12", "16", "10"], bonneReponse: 0, theme: "Mathématiques", difficulte: "facile" },
    { id: 12, question: "Combien de degrés dans un triangle ?", reponses: ["180°", "360°", "90°", "270°"], bonneReponse: 0, theme: "Mathématiques", difficulte: "facile" },
    { id: 13, question: "Quel est le quart de 20 ?", reponses: ["5", "10", "4", "8"], bonneReponse: 0, theme: "Mathématiques", difficulte: "facile" },
    { id: 14, question: "Combien vaut 100 ÷ 10 ?", reponses: ["10", "5", "15", "20"], bonneReponse: 0, theme: "Mathématiques", difficulte: "facile" },
    { id: 15, question: "Quelle est la moitié de 30 ?", reponses: ["15", "10", "20", "25"], bonneReponse: 0, theme: "Mathématiques", difficulte: "facile" },
    // Moyennes (15)
    { id: 16, question: "Combien vaut π approximativement ?", reponses: ["3,14", "2,71", "1,41", "1,73"], bonneReponse: 0, theme: "Mathématiques", difficulte: "moyen" },
    { id: 17, question: "Quel est le triple de 5 ?", reponses: ["15", "10", "20", "12"], bonneReponse: 0, theme: "Mathématiques", difficulte: "moyen" },
    { id: 18, question: "Combien vaut 7 × 8 ?", reponses: ["56", "54", "58", "60"], bonneReponse: 0, theme: "Mathématiques", difficulte: "moyen" },
    { id: 19, question: "Quel est le résultat de 9 + 6 ?", reponses: ["15", "14", "16", "17"], bonneReponse: 0, theme: "Mathématiques", difficulte: "moyen" },
    { id: 20, question: "Quel nombre est le plus grand : 45 ou 54 ?", reponses: ["54", "45", "Égal", "Impossible à dire"], bonneReponse: 0, theme: "Mathématiques", difficulte: "moyen" },
    { id: 21, question: "Combien vaut 6 × 6 ?", reponses: ["36", "42", "30", "48"], bonneReponse: 0, theme: "Mathématiques", difficulte: "moyen" },
    { id: 22, question: "Quel est le dixième de 100 ?", reponses: ["10", "5", "20", "50"], bonneReponse: 0, theme: "Mathématiques", difficulte: "moyen" },
    { id: 23, question: "Combien vaut 20 + 30 - 10 ?", reponses: ["40", "35", "45", "50"], bonneReponse: 0, theme: "Mathématiques", difficulte: "moyen" },
    { id: 24, question: "Quel est le résultat de 9 × 9 ?", reponses: ["81", "72", "90", "99"], bonneReponse: 0, theme: "Mathématiques", difficulte: "moyen" },
    { id: 25, question: "Combien vaut 18 ÷ 3 ?", reponses: ["6", "5", "7", "8"], bonneReponse: 0, theme: "Mathématiques", difficulte: "moyen" },
    { id: 26, question: "Quel est le résultat de 11 + 11 ?", reponses: ["22", "20", "24", "26"], bonneReponse: 0, theme: "Mathématiques", difficulte: "moyen" },
    { id: 27, question: "Combien vaut 12 - 8 ?", reponses: ["4", "3", "5", "6"], bonneReponse: 0, theme: "Mathématiques", difficulte: "moyen" },
    { id: 28, question: "Combien vaut (5 + 3) × 2 ?", reponses: ["16", "18", "14", "20"], bonneReponse: 0, theme: "Mathématiques", difficulte: "moyen" },
    { id: 29, question: "Quel est le résultat de 15 + 5 ?", reponses: ["20", "18", "22", "25"], bonneReponse: 0, theme: "Mathématiques", difficulte: "moyen" },
    { id: 30, question: "Combien vaut 25% de 80 ?", reponses: ["20", "15", "25", "30"], bonneReponse: 0, theme: "Mathématiques", difficulte: "moyen" },
    // Difficiles (15)
    { id: 31, question: "Résoudre x : 2x + 5 = 15", reponses: ["5", "10", "3", "7"], bonneReponse: 0, theme: "Mathématiques", difficulte: "difficile" },
    { id: 32, question: "Quelle est la racine carrée de 144 ?", reponses: ["12", "14", "10", "15"], bonneReponse: 0, theme: "Mathématiques", difficulte: "difficile" },
    { id: 33, question: "Combien vaut 3⁴ ?", reponses: ["81", "64", "27", "243"], bonneReponse: 0, theme: "Mathématiques", difficulte: "difficile" },
    { id: 34, question: "Quel est le PGCD de 48 et 36 ?", reponses: ["12", "6", "18", "24"], bonneReponse: 0, theme: "Mathématiques", difficulte: "difficile" },
    { id: 35, question: "Quel est le PPCM de 12 et 18 ?", reponses: ["36", "24", "30", "48"], bonneReponse: 0, theme: "Mathématiques", difficulte: "difficile" },
    { id: 36, question: "Résoudre y : 3y - 7 = 2", reponses: ["3", "2", "4", "5"], bonneReponse: 0, theme: "Mathématiques", difficulte: "difficile" },
    { id: 37, question: "Combien vaut (2/3) × (3/4) ?", reponses: ["1/2", "1/3", "2/3", "3/4"], bonneReponse: 0, theme: "Mathématiques", difficulte: "difficile" },
    { id: 38, question: "Quelle est la surface d'un carré de côté 5 cm ?", reponses: ["25 cm²", "20 cm²", "15 cm²", "30 cm²"], bonneReponse: 0, theme: "Mathématiques", difficulte: "difficile" },
    { id: 39, question: "Quel est le volume d'un cube de côté 3 cm ?", reponses: ["27 cm³", "9 cm³", "18 cm³", "36 cm³"], bonneReponse: 0, theme: "Mathématiques", difficulte: "difficile" },
    { id: 40, question: "Combien vaut la moyenne de 10, 20, 30 ?", reponses: ["20", "25", "15", "30"], bonneReponse: 0, theme: "Mathématiques", difficulte: "difficile" },
    { id: 41, question: "Résoudre x : x² = 25", reponses: ["5", "25", "2", "10"], bonneReponse: 0, theme: "Mathématiques", difficulte: "difficile" },
    { id: 42, question: "Quel est le périmètre d'un carré de côté 8 cm ?", reponses: ["32 cm", "64 cm", "16 cm", "24 cm"], bonneReponse: 0, theme: "Mathématiques", difficulte: "difficile" },
    { id: 43, question: "Combien vaut 20% de 250 ?", reponses: ["50", "40", "60", "70"], bonneReponse: 0, theme: "Mathématiques", difficulte: "difficile" },
    { id: 44, question: "Quel est le diamètre d'un cercle de rayon 7 cm ?", reponses: ["14 cm", "7 cm", "21 cm", "28 cm"], bonneReponse: 0, theme: "Mathématiques", difficulte: "difficile" },
    { id: 45, question: "Combien vaut 1/2 + 1/3 ?", reponses: ["5/6", "2/5", "3/5", "1/5"], bonneReponse: 0, theme: "Mathématiques", difficulte: "difficile" },
  ],

  'Physique': [
    { id: 31, question: "Quelle est la vitesse de la lumière ?", reponses: ["300 000 km/s", "150 000 km/s", "450 000 km/s", "100 000 km/s"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 32, question: "Quelle est l'unité de la force ?", reponses: ["Newton", "Joule", "Watt", "Pascal"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 33, question: "Quel est le zéro absolu en Celsius ?", reponses: ["-273°C", "-100°C", "-300°C", "-200°C"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 34, question: "Qu'est-ce que l'énergie cinétique ?", reponses: ["Énergie due au mouvement", "Énergie thermique", "Énergie potentielle", "Énergie électrique"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 35, question: "Quelle est l'unité de la puissance ?", reponses: ["Watt", "Joule", "Newton", "Volt"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 36, question: "Quelle accélération due à la pesanteur sur Terre ?", reponses: ["9,8 m/s²", "10 m/s²", "15 m/s²", "5 m/s²"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 37, question: "Quelle est la formule de la loi d'Ohm ?", reponses: ["U = RI", "U = R/I", "I = R/U", "R = U/I"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 38, question: "Quelle particule a une charge négative ?", reponses: ["Électron", "Proton", "Neutron", "Photon"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 39, question: "Quelle est l'unité de la charge électrique ?", reponses: ["Coulomb", "Joule", "Newton", "Volt"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 40, question: "Pourquoi le ciel est-il bleu ?", reponses: ["Diffusion de la lumière bleue", "Réflexion de la mer", "La lumière bleue voyage plus vite", "Absorption de la rouge"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 41, question: "Qu'est-ce qu'un trou noir ?", reponses: ["Région où la gravité empêche l'échappement", "Une étoile très dense", "Une planète sombre", "Un vide spatial"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 42, question: "Quelle est la différence entre masse et poids ?", reponses: ["La masse est invariable, le poids varie", "Aucune différence", "Le poids est plus grand", "La masse est le poids"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 43, question: "Qu'est-ce que l'effet photoélectrique ?", reponses: ["Émission d'électrons sous lumière", "Chaleur produite par lumière", "Réflexion de la lumière", "Création de lumière"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 44, question: "Pourquoi la glace flotte sur l'eau ?", reponses: ["Sa densité est plus faible", "Elle est plus froide", "Elle est plus légère", "Pression atmosphérique"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 45, question: "Qu'est-ce que la radioactivité ?", reponses: ["Désintégration de noyaux instables", "Émission de chaleur", "Réaction chimique", "Mouvement d'électrons"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 46, question: "Qu'est-ce que l'effet Doppler ?", reponses: ["Changement de fréquence du mouvement", "Changement de couleur", "Réflexion du son", "Amplification du son"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 47, question: "Quelle est la vitesse du son dans l'air ?", reponses: ["340 m/s", "150 m/s", "500 m/s", "1000 m/s"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 48, question: "Quel instrument mesure l'intensité du courant ?", reponses: ["Ampèremètre", "Voltmètre", "Ohmmètre", "Wattmètre"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 49, question: "Quel instrument mesure la tension électrique ?", reponses: ["Voltmètre", "Ampèremètre", "Ohmmètre", "Wattmètre"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 50, question: "Qu'est-ce qu'un circuit en série ?", reponses: ["Composants connectés successivement", "Composants en parallèle", "Circuit fermé", "Circuit ouvert"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 51, question: "Quelle est la nature du courant domestique ?", reponses: ["Alternatif", "Continu", "Triphasé", "Statique"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 52, question: "Lequel est un isolant électrique ?", reponses: ["Verre", "Cuivre", "Aluminium", "Fer"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 53, question: "Qu'est-ce que la période d'une onde ?", reponses: ["Durée d'une oscillation", "Nombre d'oscillations par seconde", "Longueur d'onde", "Amplitude maximale"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 54, question: "Qu'est-ce que la longueur d'onde ?", reponses: ["Distance entre deux pics", "Durée d'une oscillation", "Nombre d'oscillations", "Amplitude maximale"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 55, question: "Qui a formulé la loi de la gravitation ?", reponses: ["Isaac Newton", "Albert Einstein", "Galilée", "Stephen Hawking"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 56, question: "Qu'est-ce qu'un aimant ?", reponses: ["Objet produisant un champ magnétique", "Objet qui absorbe la chaleur", "Objet qui produit de la lumière", "Objet conducteur"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 57, question: "Quelle est la principale source d'énergie du Soleil ?", reponses: ["Fusion nucléaire", "Fission nucléaire", "Combustion chimique", "Énergie géothermale"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 58, question: "Qu'est-ce que la réfraction ?", reponses: ["Déviation de la lumière en changeant de milieu", "Rebond de la lumière", "Absorption de la lumière", "Création de lumière"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 59, question: "Qu'est-ce que la réflexion ?", reponses: ["Rebond de la lumière sur une surface", "Déviation de la lumière", "Absorption de la lumière", "Création de lumière"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
    { id: 60, question: "Combien de dimensions a l'espace-temps selon Einstein ?", reponses: ["4", "3", "2", "5"], bonneReponse: 0, theme: "Physique", difficulte: "facile" },
  ],

  'Histoire': [
    { id: 61, question: "En quelle année l'homme a-t-il marché sur la Lune ?", reponses: ["1969", "1965", "1975", "1960"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 62, question: "En quelle année la Bastille a-t-elle été prise ?", reponses: ["1789", "1799", "1779", "1809"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 63, question: "Qui a découvert l'Amérique ?", reponses: ["Christophe Colomb", "Leif Erikson", "Vasco de Gama", "Magellan"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 64, question: "En quelle année Napoléon est-il né ?", reponses: ["1769", "1759", "1779", "1789"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 65, question: "Quel est le nom du roi français Louis XIV ?", reponses: ["Le Roi Soleil", "Le Roi Prudent", "Le Roi Sage", "Le Roi Fort"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 66, question: "En quelle année a commencé la Première Guerre mondiale ?", reponses: ["1914", "1912", "1916", "1918"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 67, question: "En quelle année a commencé la Seconde Guerre mondiale ?", reponses: ["1939", "1937", "1941", "1943"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 68, question: "Quel empereur a construit la Grande Muraille de Chine ?", reponses: ["Qin Shi Huang", "Kangxi", "Yongzheng", "Qianlong"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 69, question: "Quel philosophe a écrit 'Je pense donc je suis' ?", reponses: ["René Descartes", "Jean-Jacques Rousseau", "Voltaire", "Denis Diderot"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 70, question: "En quelle année la Révolution française a-t-elle commencé ?", reponses: ["1789", "1799", "1779", "1809"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 71, question: "Quel est le premier président des États-Unis ?", reponses: ["George Washington", "Thomas Jefferson", "John Adams", "Benjamin Franklin"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 72, question: "En quelle année l'Algérie a-t-elle accédé à l'indépendance ?", reponses: ["1962", "1960", "1964", "1958"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 73, question: "Quel roi a signé la Magna Carta en Angleterre ?", reponses: ["Jean sans Terre", "Henri III", "Édouard I", "Guillaume le Conquérant"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 74, question: "En quelle année la Grande Famine irlandaise a-t-elle commencé ?", reponses: ["1845", "1835", "1855", "1865"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 75, question: "Quel empire a construit le Colosseum ?", reponses: ["Romain", "Grec", "Égyptien", "Perse"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 76, question: "En quelle année le mur de Berlin est-il tombé ?", reponses: ["1989", "1987", "1991", "1985"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 77, question: "Quel peuple a construit Machu Picchu ?", reponses: ["Les Incas", "Les Aztèques", "Les Mayas", "Les Muiscas"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 78, question: "En quelle année la déclaration d'indépendance américaine a-t-elle été signée ?", reponses: ["1776", "1774", "1778", "1780"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 79, question: "Quel compositeur a composé la 9ème Symphonie ?", reponses: ["Ludwig van Beethoven", "Wolfgang Amadeus Mozart", "Joseph Haydn", "Franz Schubert"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 80, question: "En quelle année Martin Luther King a-t-il prononcé son célèbre discours ?", reponses: ["1963", "1961", "1965", "1967"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 82, question: "Quel créateur a produit la théorie de l'évolution ?", reponses: ["Charles Darwin", "Jean-Baptiste Lamarck", "Gregor Mendel", "Gould Stephen"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 83, question: "En quelle année l'imprimerie a-t-elle été inventée par Gutenberg ?", reponses: ["1440", "1420", "1460", "1480"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 84, question: "Quel est le siècle du Siècle des Lumières ?", reponses: ["XVIII", "XVII", "XIX", "XVI"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 85, question: "En quelle année Christophe Colomb a-t-il découvert l'Amérique ?", reponses: ["1492", "1490", "1494", "1500"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 86, question: "Quel roi français a construit le château de Versailles ?", reponses: ["Louis XIV", "Louis XIII", "Louis XV", "Louis XVI"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 87, question: "En quelle année la vaccine anti-variole a-t-elle été créée ?", reponses: ["1796", "1786", "1806", "1816"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 88, question: "Quel empire a construit l'Acropole d'Athènes ?", reponses: ["Grec", "Romain", "Persan", "Égyptien"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 89, question: "En quelle année Neil Armstrong a-t-il marché sur la Lune ?", reponses: ["1969", "1967", "1971", "1965"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
    { id: 90, question: "Quel écrivain a écrit 'Les Misérables' ?", reponses: ["Victor Hugo", "Honoré de Balzac", "Gustave Flaubert", "Alexandre Dumas"], bonneReponse: 0, theme: "Histoire", difficulte: "facile" },
  ],

  'Géographie': [
    { id: 91, question: "Quelle est la capitale de la France ?", reponses: ["Paris", "Lyon", "Marseille", "Toulouse"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 92, question: "Quel est le plus haut sommet du monde ?", reponses: ["Mont Everest", "K2", "Kangchenjunga", "Makalu"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 93, question: "Quel est le plus grand océan du monde ?", reponses: ["Océan Pacifique", "Océan Atlantique", "Océan Indien", "Océan Arctique"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 94, question: "Quel est le plus grand désert du monde ?", reponses: ["Sahara", "Kalahari", "Gobi", "Arabie"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 95, question: "Quel est le plus long fleuve du monde ?", reponses: ["Nil", "Amazone", "Yangtsé", "Mississippi"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 96, question: "Quel est le plus grand lac du monde ?", reponses: ["Mer Caspienne", "Lac Baïkal", "Lac Victoria", "Lac Supérieur"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 97, question: "Quelle est la capitale de l'Angleterre ?", reponses: ["Londres", "Manchester", "Liverpool", "Birmingham"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 98, question: "Quelle est la capitale de l'Espagne ?", reponses: ["Madrid", "Barcelone", "Valence", "Séville"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 99, question: "Quelle est la capitale de l'Italie ?", reponses: ["Rome", "Milan", "Naples", "Venise"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 100, question: "Quelle est la capitale de l'Allemagne ?", reponses: ["Berlin", "Munich", "Hambourg", "Cologne"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 101, question: "Quel est le plus grand pays du monde ?", reponses: ["Russie", "Canada", "Chine", "États-Unis"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 102, question: "Quel est le plus petit pays du monde ?", reponses: ["Vatican", "Monaco", "Liechtenstein", "Andorre"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 103, question: "Quelle est la capitale du Canada ?", reponses: ["Ottawa", "Toronto", "Vancouver", "Montréal"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 104, question: "Quelle est la capitale de l'Australie ?", reponses: ["Canberra", "Sydney", "Melbourne", "Brisbane"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 105, question: "Quel continent a la plus grande population ?", reponses: ["Asie", "Afrique", "Europe", "Amérique du Nord"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 106, question: "Quelle est la capitale du Japon ?", reponses: ["Tokyo", "Kyoto", "Osaka", "Yokohama"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 107, question: "Quelle est la capitale de la Suisse ?", reponses: ["Berne", "Zurich", "Genève", "Lausanne"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 108, question: "Quel est le plus haut pic d'Afrique ?", reponses: ["Kilimandjaro", "Mont Kenya", "Ruwenzori", "Pic de Stanley"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 109, question: "Quelle est la plus grande forêt du monde ?", reponses: ["Amazonie", "Forêt du Congo", "Taïga sibérienne", "Forêt tropicale du Kalimantan"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 110, question: "Quel est le climat dominant du Sahara ?", reponses: ["Désertique", "Tropical", "Méditerranéen", "Subtropical"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 111, question: "Quelle est la capitale de la Thaïlande ?", reponses: ["Bangkok", "Phuket", "Chiang Mai", "Pattaya"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 112, question: "Quel est le plus grand archipel du monde ?", reponses: ["Indonésie", "Philippines", "Polynésie française", "Caraïbes"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 113, question: "Quelle est la capitale de la Suède ?", reponses: ["Stockholm", "Göteborg", "Malmö", "Uppsala"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 114, question: "Quel est le fleuve le plus important d'Afrique ?", reponses: ["Nil", "Congo", "Niger", "Zambèze"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 115, question: "Quelle est la capitale de la Belgique ?", reponses: ["Bruxelles", "Anvers", "Gand", "Charleroi"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 116, question: "Quelle est la capitale des Pays-Bas ?", reponses: ["Amsterdam", "Rotterdam", "La Haye", "Utrecht"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 117, question: "Quelle est la capitale de la Grèce ?", reponses: ["Athènes", "Thessalonique", "Patras", "Larissa"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 118, question: "Quel est le deuxième plus grand continent en surface ?", reponses: ["Afrique", "Amérique du Nord", "Asie", "Europe"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 119, question: "Quelle est la capitale de la Norvège ?", reponses: ["Oslo", "Bergen", "Stavanger", "Trondheim"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
    { id: 120, question: "Quel est le plus grand lac d'Europe ?", reponses: ["Ladoga", "Onega", "Balkhash", "Tanganyika"], bonneReponse: 0, theme: "Géographie", difficulte: "facile" },
  ],

  'Informatique': [
    { id: 121, question: "Quel est l'ancêtre de l'internet moderne ?", reponses: ["ARPANET", "USENET", "Ethernet", "Token Ring"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 122, question: "Quel est le langage de balisage utilisé sur le web ?", reponses: ["HTML", "CSS", "JavaScript", "Python"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 123, question: "Quel est l'inventeur du web ?", reponses: ["Tim Berners-Lee", "Bill Gates", "Steve Jobs", "Larry Page"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 124, question: "Quel système d'exploitation a été créé par Linus Torvalds ?", reponses: ["Linux", "Windows", "macOS", "Android"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 125, question: "Quel est le fondateur de Microsoft ?", reponses: ["Bill Gates", "Steve Jobs", "Mark Zuckerberg", "Elon Musk"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 126, question: "Quel est le fondateur d'Apple ?", reponses: ["Steve Jobs", "Bill Gates", "Mark Zuckerberg", "Elon Musk"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 127, question: "Quel est le langage de programmation le plus utilisé ?", reponses: ["Python", "JavaScript", "Java", "C++"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 128, question: "Quel est le plus grand moteur de recherche ?", reponses: ["Google", "Bing", "Yahoo", "DuckDuckGo"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 129, question: "Qui a inventé le langage C ?", reponses: ["Dennis Ritchie", "Bjarne Stroustrup", "Guido van Rossum", "Brendan Eich"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 130, question: "Quel est le système d'exploitation le plus utilisé ?", reponses: ["Windows", "macOS", "Linux", "Android"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 131, question: "Quel est le fondateur de Facebook ?", reponses: ["Mark Zuckerberg", "Bill Gates", "Steve Jobs", "Jack Dorsey"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 132, question: "Quel est le fondateur de Twitter ?", reponses: ["Jack Dorsey", "Mark Zuckerberg", "Bill Gates", "Steve Jobs"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 133, question: "Quel est le format de fichier image le plus courant ?", reponses: ["JPEG", "PNG", "GIF", "BMP"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 134, question: "Quel est le protocole utilisé pour le courrier électronique ?", reponses: ["SMTP", "HTTP", "FTP", "DNS"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 135, question: "Quel est le langage utilisé pour les styles web ?", reponses: ["CSS", "HTML", "JavaScript", "Python"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 136, question: "Quel est le principal langage de programmation web côté client ?", reponses: ["JavaScript", "Python", "Java", "C++"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 137, question: "Quel est le type de données qui peut être vrai ou faux ?", reponses: ["Boolean", "Integer", "String", "Float"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 138, question: "Quel est le fondateur d'Amazon ?", reponses: ["Jeff Bezos", "Elon Musk", "Mark Zuckerberg", "Steve Jobs"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 139, question: "Quel est le langage utilisé pour les requêtes de base de données ?", reponses: ["SQL", "HTML", "CSS", "JavaScript"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 140, question: "Quel est le port par défaut pour HTTP ?", reponses: ["80", "443", "8080", "3306"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 141, question: "Quel est le port par défaut pour HTTPS ?", reponses: ["443", "80", "8080", "3306"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 142, question: "Quel est le fondateur de Tesla ?", reponses: ["Elon Musk", "Jeff Bezos", "Mark Zuckerberg", "Steve Jobs"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 143, question: "Quel est le sigle d'une adresse internet ?", reponses: ["URL", "HTML", "CSS", "DNS"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 144, question: "Quel est le système de fichiers de Windows ?", reponses: ["NTFS", "FAT32", "ext4", "APFS"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 145, question: "Quel est le élément principal d'une page web ?", reponses: ["<html>", "<head>", "<body>", "<div>"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 146, question: "Quel est le navigateur web le plus utilisé ?", reponses: ["Chrome", "Firefox", "Safari", "Edge"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 147, question: "Quel est le sigle d'une base de données ?", reponses: ["DB", "SQL", "HTML", "CSS"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 148, question: "Quel est le protocole sécurisé pour le web ?", reponses: ["HTTPS", "HTTP", "FTP", "SMTP"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 149, question: "Quel est le format de fichier compressé le plus courant ?", reponses: ["ZIP", "TAR", "7Z", "RAR"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
    { id: 150, question: "Quel est le langage de balisage pour les documents XML ?", reponses: ["XML", "HTML", "CSS", "JSON"], bonneReponse: 0, theme: "Informatique", difficulte: "facile" },
  ],
};

export const themesDisponibles = Object.keys(questionsSimples);

export function obtenirQuestionsParTheme(theme: string, nombreQuestions: number): Question[] {
  const questions = questionsSimples[theme] || [];
  const melangees = [...questions].sort(() => Math.random() - 0.5);
  return melangees.slice(0, nombreQuestions);
}
